apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml
  template:
    metadata:
      labels:
        app: ml
    spec:
      containers:
        - name: ml
          image: mdkaifraza/ccps-ml:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5001
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"