apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
stringData:
  JWT_SECRET: "your_jwt_secret"
  CLOUDINARY_API_SECRET: "aeHG64IE5yFHIdDwv1GkdELPNRQ"
  SMTP_PASSWORD: "edgu rwdt gkfl odav"